version: "3.1"
services:
  equipadh-postgres:
    image: postgres:12
    container_name: equipadh-postgres
    environment:
      POSTGRES_DB: equipadh
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - default_equipadh

  equipadh-api:
    #build:
    #  context: ./deploy/dev/backend/
    #  dockerfile: ./Dockerfile
    image: equipadh-api:latest
    container_name: equipadh-api
    environment:
      REDIRECT_HTTPS: "false"
      APP_ENV: local
      APP_KEY: "base64:ExLLAecrz5xCLVP2Mp/na1CJvsgGTk7YKU6vCU5M/WY="
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      APP_URL: http://localhost
      DB_CONNECTION: pgsql

      # Database do novo sistema
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: equipadh
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_POOL_ENABLED: true
      DB_POOL_MAX_CONNECTIONS: 50
      DB_POOL_TIMEOUT: 30
      
      # Database de auditoria
      DB_HOST_AUDIT: db
      DB_DATABASE_AUDIT: equipadh
      DB_USERNAME_AUDIT: postgres
      DB_PASSWORD_AUDIT: postgres
      DB_SCHEMA_AUDIT: audit_equipadh
      DB_SAVE_AUDIT: "false"
  
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ministeriodosdireitoshumanos2@gmail.com
      MAIL_PASSWORD: gcprwqcbdelznbmd
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: ministeriodosdireitoshumanos2@gmail.com
      MAIL_FROM_NAME: ministeriodosdireitoshumanos2@gmail.com
      PUSHER_APP_ID:
      PUSHER_KEY:
      PUSHER_SECRET:
      JWT_SECRET: 'YUmm6hY7JOEOTBTJIx7pQVXNybu5TfUQqPPZ2RCpup5qOwwg2Jq1c71beX0GEwS4'
      RECAPTCHA_SITE_KEY: '6LeWYaUUAAAAAJ_0S4Yt8nm9Kov4kyhBYMxLbmXq'
      RECAPTCHA_SECRET_KEY: '6LeWYaUUAAAAAH0MC5dpHke7wHFAK54DMklVi_Gv'
      URL_FRONT: 'http://localhost:8080'
      AUTH_URL_FRONT: https://autenticador-dev.hlog.mdh.gov.br
      AUTH_URL_API: https://api-autenticador-dev.hlog.mdh.gov.br/api
      AUTH_CLIENT_ID: equipadh-local
      AUTH_CLIENT_SECRET: 123456
      AUTH_SIGLA: equipadh-local
      AUTH_URL_LOGOUT: https://autenticador-dev.hlog.mdh.gov.br/logout
      ENCRYPT_KEY: 'MPfi@240195'
      ENCRYPT_VI: 'YUmm6hY7JOEOTBTJ'
      ENCRYPT_METHOD: 'AES-128-CBC'
    volumes:
      - ./backend/:/var/www/html
    links:
      - equipadh-postgres:db
    ports:
      - "81:80"
    networks: 
      - default_equipadh
networks:
    default_equipadh:
        driver: bridge
